import { db } from "../firebase.config.ts";
import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  serverTimestamp,
} from "firebase/firestore";

// Firestore Collection: "courses"
// Document ID: auto-generated

export interface CourseDocument {
  title: string;          // required
  provider: string;       // default: ''
  category: string;       // default: ''
  duration: string;       // default: ''
  lessons: number;        // default: 0
  rating: number;         // default: 0.0
  reviewsCount: number;   // default: 0
  skillsCovered: string[];// default: []
  isFree: boolean;        // default: true
  url: string;            // default: ''
  isActive: boolean;      // default: true
  level: string;          // 'Beginner' | 'Intermediate' | 'Advanced'
  language: string;       // default: 'English'
  accessibilityFeatures: string[]; // e.g. ['Sign Language', 'Subtitles', 'Screen Reader']
  pwdFocused: boolean;    // true = specifically designed for PwD
  createdAt: any;         // serverTimestamp()
}

// Add a course (Admin only)
export const addCourse = async (courseData: Omit<CourseDocument, "createdAt">) => {
  const coursesRef = collection(db, "courses");
  await addDoc(coursesRef, { ...courseData, createdAt: serverTimestamp() });
};

// Get all active courses (public read)
export const getActiveCourses = async () => {
  const coursesRef = collection(db, "courses");
  const q = query(coursesRef, where("isActive", "==", true));
  const snap = await getDocs(q);
  return snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as CourseDocument & { id: string }));
};

// Get PwD-focused free courses only
export const getPwdFreeCourses = async () => {
  const coursesRef = collection(db, "courses");
  const q = query(
    coursesRef,
    where("isActive", "==", true),
    where("isFree", "==", true),
    where("pwdFocused", "==", true)
  );
  const snap = await getDocs(q);
  return snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as CourseDocument & { id: string }));
};

// ── Free PwD Courses Seed Data ────────────────────────────────────────────────
export const pwdFreeCourses: Omit<CourseDocument, "createdAt">[] = [

  // ── PM-DAKSH / DEPwD Courses ──────────────────────────────────────────────
  {
    title: "Employability Skills for Persons with Disabilities",
    provider: "PM-DAKSH (DEPwD, Govt. of India)",
    category: "Employability",
    duration: "40 Hours",
    lessons: 20,
    rating: 4.5,
    reviewsCount: 0,
    skillsCovered: ["Communication", "Resume Writing", "Interview Skills", "Workplace Etiquette"],
    isFree: true,
    url: "https://pmdaksh.depwd.gov.in/courses_offered",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Digital Literacy for PwD",
    provider: "PM-DAKSH (DEPwD, Govt. of India)",
    category: "Digital Skills",
    duration: "30 Hours",
    lessons: 15,
    rating: 4.3,
    reviewsCount: 0,
    skillsCovered: ["Computer Basics", "Internet Usage", "Email", "MS Office", "Online Safety"],
    isFree: true,
    url: "https://pmdaksh.depwd.gov.in/courses_offered",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi, Regional Languages",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Beauty & Wellness Training for PwD",
    provider: "PM-DAKSH (DEPwD, Govt. of India)",
    category: "Vocational",
    duration: "200 Hours",
    lessons: 30,
    rating: 4.2,
    reviewsCount: 0,
    skillsCovered: ["Grooming", "Skin Care", "Hair Care", "Salon Management"],
    isFree: true,
    url: "https://pmdaksh.depwd.gov.in/courses_offered",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Bakery & Food Production for PwD",
    provider: "PM-DAKSH (DEPwD, Govt. of India)",
    category: "Vocational",
    duration: "180 Hours",
    lessons: 25,
    rating: 4.1,
    reviewsCount: 0,
    skillsCovered: ["Baking", "Food Safety", "Recipe Preparation", "Packaging"],
    isFree: true,
    url: "https://pmdaksh.depwd.gov.in/courses_offered",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles"],
    pwdFocused: true,
  },
  {
    title: "Handicrafts & Artisan Skills for PwD",
    provider: "PM-DAKSH (DEPwD, Govt. of India)",
    category: "Vocational",
    duration: "150 Hours",
    lessons: 20,
    rating: 4.0,
    reviewsCount: 0,
    skillsCovered: ["Craftsmanship", "Weaving", "Pottery", "Painting", "Product Design"],
    isFree: true,
    url: "https://pmdaksh.depwd.gov.in/courses_offered",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi, Regional Languages",
    accessibilityFeatures: ["Sign Language", "Subtitles"],
    pwdFocused: true,
  },

  // ── SCPwD (Skill Council for Persons with Disability) ─────────────────────
  {
    title: "IT/ITeS – Customer Support Associate",
    provider: "Skill Council for Persons with Disability (SCPwD)",
    category: "IT & Technology",
    duration: "250 Hours",
    lessons: 35,
    rating: 4.4,
    reviewsCount: 0,
    skillsCovered: ["Customer Service", "BPO Skills", "Communication", "Computer Basics"],
    isFree: true,
    url: "https://www.scpwd.in/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Retail Sales Associate Training",
    provider: "Skill Council for Persons with Disability (SCPwD)",
    category: "Retail",
    duration: "200 Hours",
    lessons: 28,
    rating: 4.2,
    reviewsCount: 0,
    skillsCovered: ["Sales Techniques", "Customer Handling", "Inventory Management", "POS Systems"],
    isFree: true,
    url: "https://www.scpwd.in/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles"],
    pwdFocused: true,
  },
  {
    title: "Hospitality & Tourism for PwD",
    provider: "Skill Council for Persons with Disability (SCPwD)",
    category: "Hospitality",
    duration: "220 Hours",
    lessons: 30,
    rating: 4.3,
    reviewsCount: 0,
    skillsCovered: ["Front Desk Operations", "Housekeeping", "Guest Relations", "Food & Beverage"],
    isFree: true,
    url: "https://www.scpwd.in/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Healthcare Support Worker",
    provider: "Skill Council for Persons with Disability (SCPwD)",
    category: "Healthcare",
    duration: "300 Hours",
    lessons: 40,
    rating: 4.5,
    reviewsCount: 0,
    skillsCovered: ["Patient Care", "First Aid", "Medical Terminology", "Health & Safety"],
    isFree: true,
    url: "https://www.scpwd.in/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles"],
    pwdFocused: true,
  },

  // ── SWAYAM / NPTEL (Ministry of Education) ────────────────────────────────
  {
    title: "Introduction to Programming using Python",
    provider: "NPTEL / SWAYAM",
    category: "Programming",
    duration: "8 Weeks",
    lessons: 40,
    rating: 4.7,
    reviewsCount: 5000,
    skillsCovered: ["Python", "Programming Basics", "Data Structures", "Problem Solving"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Downloadable Transcripts"],
    pwdFocused: false,
  },
  {
    title: "Data Science for Engineers",
    provider: "NPTEL / SWAYAM",
    category: "Data Science",
    duration: "12 Weeks",
    lessons: 60,
    rating: 4.6,
    reviewsCount: 3500,
    skillsCovered: ["Statistics", "Python", "Machine Learning", "Data Visualization"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Intermediate",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Downloadable Transcripts"],
    pwdFocused: false,
  },
  {
    title: "English Language for Competitive Exams",
    provider: "NPTEL / SWAYAM",
    category: "Language",
    duration: "8 Weeks",
    lessons: 32,
    rating: 4.4,
    reviewsCount: 2800,
    skillsCovered: ["Grammar", "Vocabulary", "Reading Comprehension", "Writing Skills"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible"],
    pwdFocused: false,
  },
  {
    title: "Joy of Computing using Python",
    provider: "NPTEL / SWAYAM",
    category: "Programming",
    duration: "12 Weeks",
    lessons: 48,
    rating: 4.8,
    reviewsCount: 8000,
    skillsCovered: ["Python", "Algorithms", "Computational Thinking", "Web Scraping"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Downloadable Transcripts"],
    pwdFocused: false,
  },
  {
    title: "Cloud Computing",
    provider: "NPTEL / SWAYAM",
    category: "Cloud & DevOps",
    duration: "12 Weeks",
    lessons: 50,
    rating: 4.5,
    reviewsCount: 4200,
    skillsCovered: ["Cloud Architecture", "AWS Basics", "Virtualization", "Cloud Security"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Intermediate",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Downloadable Transcripts"],
    pwdFocused: false,
  },
  {
    title: "Soft Skills & Personality Development",
    provider: "NPTEL / SWAYAM",
    category: "Soft Skills",
    duration: "8 Weeks",
    lessons: 30,
    rating: 4.6,
    reviewsCount: 6000,
    skillsCovered: ["Communication", "Leadership", "Time Management", "Teamwork", "Confidence Building"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible"],
    pwdFocused: false,
  },
  {
    title: "Financial Literacy & Money Management",
    provider: "NPTEL / SWAYAM",
    category: "Finance",
    duration: "6 Weeks",
    lessons: 24,
    rating: 4.4,
    reviewsCount: 2200,
    skillsCovered: ["Budgeting", "Savings", "Banking Basics", "Investments", "Insurance"],
    isFree: true,
    url: "https://onlinecourses.nptel.ac.in/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles", "Downloadable Transcripts"],
    pwdFocused: false,
  },

  // ── Enable India Courses ──────────────────────────────────────────────────
  {
    title: "Assistive Technology for Visual Impairment",
    provider: "Enable India",
    category: "Assistive Technology",
    duration: "6 Weeks",
    lessons: 18,
    rating: 4.7,
    reviewsCount: 0,
    skillsCovered: ["Screen Readers", "JAWS", "NVDA", "Braille Literacy", "Digital Accessibility"],
    isFree: true,
    url: "http://www.enableindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Screen Reader Compatible", "Audio Description", "Braille Materials"],
    pwdFocused: true,
  },
  {
    title: "Job Readiness & Placement Training for PwD",
    provider: "Enable India",
    category: "Employability",
    duration: "4 Weeks",
    lessons: 16,
    rating: 4.6,
    reviewsCount: 0,
    skillsCovered: ["Interview Preparation", "Resume Writing", "Workplace Communication", "Self Advocacy"],
    isFree: true,
    url: "http://www.enableindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Digital Accessibility & Self Employment",
    provider: "Enable India",
    category: "Entrepreneurship",
    duration: "5 Weeks",
    lessons: 20,
    rating: 4.5,
    reviewsCount: 0,
    skillsCovered: ["Online Business", "Digital Marketing", "E-commerce", "Freelancing"],
    isFree: true,
    url: "http://www.enableindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Screen Reader Compatible", "Audio Description"],
    pwdFocused: true,
  },

  // ── Sarthak Educational Trust / GyanSarathi ───────────────────────────────
  {
    title: "Computer Fundamentals & MS Office",
    provider: "Sarthak Educational Trust (GyanSarathi)",
    category: "Digital Skills",
    duration: "60 Hours",
    lessons: 20,
    rating: 4.4,
    reviewsCount: 0,
    skillsCovered: ["MS Word", "MS Excel", "MS PowerPoint", "Internet Basics", "Email"],
    isFree: true,
    url: "https://www.sarthakindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },
  {
    title: "Spoken English for PwD Job Seekers",
    provider: "Sarthak Educational Trust (GyanSarathi)",
    category: "Language",
    duration: "40 Hours",
    lessons: 15,
    rating: 4.3,
    reviewsCount: 0,
    skillsCovered: ["Spoken English", "Pronunciation", "Listening Skills", "Interview English"],
    isFree: true,
    url: "https://www.sarthakindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles"],
    pwdFocused: true,
  },
  {
    title: "Entrepreneurship for Persons with Disabilities",
    provider: "Sarthak Educational Trust (GyanSarathi)",
    category: "Entrepreneurship",
    duration: "50 Hours",
    lessons: 18,
    rating: 4.5,
    reviewsCount: 0,
    skillsCovered: ["Business Planning", "Marketing", "Finance Basics", "Govt Schemes", "Self Employment"],
    isFree: true,
    url: "https://www.sarthakindia.org/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Sign Language", "Subtitles", "Screen Reader Compatible"],
    pwdFocused: true,
  },

  // ── Coursera (Free Audit) ─────────────────────────────────────────────────
  {
    title: "Introduction to Web Development",
    provider: "Coursera (Meta – Free Audit)",
    category: "Web Development",
    duration: "4 Weeks",
    lessons: 22,
    rating: 4.7,
    reviewsCount: 12000,
    skillsCovered: ["HTML", "CSS", "JavaScript Basics", "Responsive Design"],
    isFree: true,
    url: "https://www.coursera.org/learn/introduction-to-web-development",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Transcripts", "Screen Reader Compatible"],
    pwdFocused: false,
  },
  {
    title: "Google IT Support Professional Certificate",
    provider: "Coursera (Google – Financial Aid Available)",
    category: "IT & Technology",
    duration: "6 Months",
    lessons: 120,
    rating: 4.8,
    reviewsCount: 25000,
    skillsCovered: ["IT Support", "Networking", "Operating Systems", "Security", "Cloud Computing"],
    isFree: true,
    url: "https://www.coursera.org/professional-certificates/google-it-support",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Transcripts", "Screen Reader Compatible"],
    pwdFocused: false,
  },
  {
    title: "Excel Skills for Business",
    provider: "Coursera (Macquarie University – Free Audit)",
    category: "Digital Skills",
    duration: "4 Weeks",
    lessons: 20,
    rating: 4.8,
    reviewsCount: 18000,
    skillsCovered: ["MS Excel", "Data Analysis", "Formulas", "Charts", "Pivot Tables"],
    isFree: true,
    url: "https://www.coursera.org/learn/excel-skills-for-business-essentials",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Transcripts"],
    pwdFocused: false,
  },

  // ── Google (Free) ─────────────────────────────────────────────────────────
  {
    title: "Fundamentals of Digital Marketing",
    provider: "Google Digital Garage",
    category: "Digital Marketing",
    duration: "40 Hours",
    lessons: 26,
    rating: 4.6,
    reviewsCount: 50000,
    skillsCovered: ["SEO", "Social Media Marketing", "Email Marketing", "Analytics", "Online Advertising"],
    isFree: true,
    url: "https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible"],
    pwdFocused: false,
  },
  {
    title: "Introduction to Generative AI",
    provider: "Google Cloud Skills Boost",
    category: "Artificial Intelligence",
    duration: "45 Minutes",
    lessons: 5,
    rating: 4.5,
    reviewsCount: 30000,
    skillsCovered: ["Generative AI", "Large Language Models", "AI Tools", "Prompt Engineering"],
    isFree: true,
    url: "https://www.cloudskillsboost.google/course_templates/536",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Transcripts"],
    pwdFocused: false,
  },

  // ── Microsoft (Free) ──────────────────────────────────────────────────────
  {
    title: "Microsoft Azure Fundamentals (AZ-900)",
    provider: "Microsoft Learn",
    category: "Cloud & DevOps",
    duration: "8 Hours",
    lessons: 20,
    rating: 4.7,
    reviewsCount: 40000,
    skillsCovered: ["Azure Cloud", "Cloud Concepts", "Azure Services", "Security", "Pricing"],
    isFree: true,
    url: "https://learn.microsoft.com/en-us/training/paths/az-900-describe-cloud-concepts/",
    isActive: true,
    level: "Beginner",
    language: "English, Hindi",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible", "Keyboard Navigation"],
    pwdFocused: false,
  },
  {
    title: "Introduction to AI with Microsoft Azure",
    provider: "Microsoft Learn",
    category: "Artificial Intelligence",
    duration: "10 Hours",
    lessons: 25,
    rating: 4.6,
    reviewsCount: 20000,
    skillsCovered: ["AI Concepts", "Machine Learning", "Computer Vision", "NLP", "Azure AI"],
    isFree: true,
    url: "https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Screen Reader Compatible", "Keyboard Navigation"],
    pwdFocused: false,
  },

  // ── NIEPMD (Govt. National Institute) ────────────────────────────────────
  {
    title: "Certificate in Community Based Inclusive Development (CBID)",
    provider: "NIEPMD (DEPwD, Govt. of India)",
    category: "Disability Studies",
    duration: "6 Months",
    lessons: 50,
    rating: 4.5,
    reviewsCount: 0,
    skillsCovered: ["Disability Awareness", "Community Inclusion", "Rehabilitation", "Advocacy"],
    isFree: true,
    url: "https://niepmd.tn.nic.in/courses.php",
    isActive: true,
    level: "Beginner",
    language: "English, Tamil, Hindi",
    accessibilityFeatures: ["Sign Language", "Accessible Materials"],
    pwdFocused: true,
  },
  {
    title: "Diploma in Vocational Rehabilitation",
    provider: "NIEPMD (DEPwD, Govt. of India)",
    category: "Vocational",
    duration: "1 Year",
    lessons: 80,
    rating: 4.6,
    reviewsCount: 0,
    skillsCovered: ["Vocational Assessment", "Job Placement", "Rehabilitation Planning", "Counseling"],
    isFree: true,
    url: "https://niepmd.tn.nic.in/courses.php",
    isActive: true,
    level: "Intermediate",
    language: "English",
    accessibilityFeatures: ["Accessible Materials"],
    pwdFocused: true,
  },

  // ── Free Coding / Tech Upskilling ─────────────────────────────────────────
  {
    title: "Responsive Web Design",
    provider: "freeCodeCamp",
    category: "Web Development",
    duration: "300 Hours",
    lessons: 100,
    rating: 4.9,
    reviewsCount: 100000,
    skillsCovered: ["HTML", "CSS", "Flexbox", "Grid", "Accessibility Standards"],
    isFree: true,
    url: "https://www.freecodecamp.org/learn/2022/responsive-web-design/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Screen Reader Compatible", "Keyboard Navigation", "High Contrast Mode"],
    pwdFocused: false,
  },
  {
    title: "JavaScript Algorithms and Data Structures",
    provider: "freeCodeCamp",
    category: "Programming",
    duration: "300 Hours",
    lessons: 100,
    rating: 4.8,
    reviewsCount: 80000,
    skillsCovered: ["JavaScript", "Algorithms", "Data Structures", "OOP", "Functional Programming"],
    isFree: true,
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
    isActive: true,
    level: "Beginner",
    language: "English",
    accessibilityFeatures: ["Screen Reader Compatible", "Keyboard Navigation"],
    pwdFocused: false,
  },
  {
    title: "Web Accessibility (WCAG Standards)",
    provider: "Google (Udacity – Free)",
    category: "Accessibility",
    duration: "2 Weeks",
    lessons: 15,
    rating: 4.7,
    reviewsCount: 15000,
    skillsCovered: ["WCAG 2.1", "ARIA", "Screen Reader Testing", "Inclusive Design", "Accessibility Auditing"],
    isFree: true,
    url: "https://www.udacity.com/course/web-accessibility--ud891",
    isActive: true,
    level: "Intermediate",
    language: "English",
    accessibilityFeatures: ["Subtitles", "Transcripts", "Screen Reader Compatible"],
    pwdFocused: false,
  },
];

// ── Seed Function ─────────────────────────────────────────────────────────────
// Run this ONCE to populate Firestore with all free PwD courses
// e.g., call seedCourses() from an admin page or a one-time script
export const seedCourses = async () => {
  const coursesRef = collection(db, "courses");
  const results = await Promise.allSettled(
    pwdFreeCourses.map((course) =>
      addDoc(coursesRef, { ...course, createdAt: serverTimestamp() })
    )
  );

  const succeeded = results.filter((r) => r.status === "fulfilled").length;
  const failed = results.filter((r) => r.status === "rejected").length;

  console.log(`✅ Seeded ${succeeded} courses successfully.`);
  if (failed > 0) console.warn(`⚠️ ${failed} courses failed to seed.`);
};