import { db } from "../firebase.config.ts";
import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  serverTimestamp,
} from "firebase/firestore";

// Firestore Collection: "schemes"
// Document ID: auto-generated

export interface SchemeDocument {
  name: string;                             // required
  ministry: string;                         // default: ''
  category: string;                         // default: ''
  description: string;                      // default: ''
  eligibilityCriteria: Record<string, any>; // default: {}
  benefits: string;                         // default: ''
  deadline: string | null;                  // ISO string or null
  maxIncome: number | null;                 // default: null
  disabilityTypes: string[];                // default: []
  educationRequired: string;                // default: ''
  isActive: boolean;                        // default: true
  applyLink: string;                        // default: ''
  documents: string[];                      // required documents list
  icon: string;                             // icon name string
  source: string;                           // default: ''
  publishDate: string;                      // default: ''
  createdAt: any;                           // serverTimestamp()
}

// Add a scheme (Admin only)
export const addScheme = async (schemeData: Omit<SchemeDocument, "createdAt">) => {
  const schemesRef = collection(db, "schemes");
  await addDoc(schemesRef, { ...schemeData, createdAt: serverTimestamp() });
};

// Get all active schemes (public read)
export const getActiveSchemes = async () => {
  const schemesRef = collection(db, "schemes");
  const q = query(schemesRef, where("isActive", "==", true));
  const snap = await getDocs(q);
  return snap.docs.map(doc => ({ id: doc.id, ...doc.data() } as SchemeDocument & { id: string }));
};

// ── Quick filter tags & education levels ─────────────────────────────────────
export const AVAILABLE_TAGS = [
  "engineering",
  "financial",
  "medical",
  "scholarship",
  "vocational",
  "entrepreneurship",
  "disability-services",
  "welfare",
  "health",
];

// ── Schemes Seed Data ─────────────────────────────────────────────────────────
// Run seedSchemes() ONCE to populate Firestore with scheme listings
export const schemesData: Omit<SchemeDocument, "createdAt">[] = [

  // ── State Government Schemes (101–111) ────────────────────────────────────
  {
    name: "Sanjay Gandhi Niradhar Yojana",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Monthly financial assistance for destitute and disabled individuals in Maharashtra.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      incomeGroup: "Below Poverty Line",
    },
    benefits: "₹1000 - ₹2500 per month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://aaplesarkar.mahaonline.gov.in",
    documents: ["Disability Certificate", "Income Certificate", "Aadhaar Card", "Bank Passbook"],
    icon: "Wallet",
    source: "",
    publishDate: "",
  },
  {
    name: "Divyang Shaadi Protsahan Yojana",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Financial assistance to encourage marriage involving persons with disabilities.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40% (at least one partner)",
    },
    benefits: "₹50,000 - ₹1,00,000 (one-time)",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://aaplesarkar.mahaonline.gov.in",
    documents: ["Marriage Certificate", "Disability Certificate", "Aadhaar Card"],
    icon: "Heart",
    source: "",
    publishDate: "",
  },
  {
    name: "Pre-Matric Scholarship for Disabled Students",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Scholarship support for school students with disabilities.",
    eligibilityCriteria: {
      educationLevel: "Class 1–10",
    },
    benefits: "₹500 - ₹1000 per month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "School (Class 1–10)",
    isActive: true,
    applyLink: "https://mahadbt.maharashtra.gov.in",
    documents: ["Disability Certificate", "School Bonafide", "Income Certificate"],
    icon: "BookOpen",
    source: "",
    publishDate: "",
  },
  {
    name: "Post-Matric Scholarship for Disabled Students",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Financial assistance for higher education of students with disabilities.",
    eligibilityCriteria: {
      educationLevel: "College or Higher Education",
    },
    benefits: "₹1000+ per month (varies)",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Higher Education",
    isActive: true,
    applyLink: "https://mahadbt.maharashtra.gov.in",
    documents: ["Disability Certificate", "College ID", "Income Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Self Employment Scheme for Disabled",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Provides financial support and subsidy for self-employment ventures.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      intent: "Start a business",
    },
    benefits: "Loan with subsidy (varies)",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://www.myscheme.gov.in",
    documents: ["Disability Certificate", "Project Report", "Aadhaar Card"],
    icon: "Briefcase",
    source: "",
    publishDate: "",
  },
  {
    name: "Aids and Appliances Scheme (ADIP + State)",
    ministry: "Department of Empowerment of Persons with Disabilities",
    category: "Central Government",
    description: "Provides assistive devices like wheelchairs, hearing aids, prosthetics.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      incomeCriteria: "As per scheme guidelines",
    },
    benefits: "Free / Subsidized equipment",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://depwd.gov.in",
    documents: ["Disability Certificate", "Income Certificate", "Aadhaar Card"],
    icon: "Accessibility",
    source: "",
    publishDate: "",
  },
  {
    name: "Caregiver Allowance Scheme",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Financial support for caregivers of persons with severe disabilities.",
    eligibilityCriteria: {
      caregiverOf: "Severely disabled persons",
    },
    benefits: "₹2000 per month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["Severe"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://aaplesarkar.mahaonline.gov.in",
    documents: ["Disability Certificate", "Aadhaar Card", "Bank Details"],
    icon: "Users",
    source: "",
    publishDate: "",
  },
  {
    name: "Indira Gandhi National Disability Pension Scheme",
    ministry: "Ministry of Rural Development",
    category: "Central Government",
    description: "Central pension scheme for severely disabled individuals.",
    eligibilityCriteria: {
      disabilityPercentage: "≥80%",
      ageRange: "18–65 years",
    },
    benefits: "₹300 - ₹600 per month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["Severe"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://nsap.nic.in",
    documents: ["Disability Certificate", "Aadhaar Card", "Income Certificate"],
    icon: "Wallet",
    source: "",
    publishDate: "",
  },
  {
    name: "Free Coaching Scheme for PwD",
    ministry: "Department of Empowerment of Persons with Disabilities",
    category: "Central Government",
    description: "Provides coaching for UPSC, SSC, Banking, etc.",
    eligibilityCriteria: {
      purpose: "Competitive exam preparation",
    },
    benefits: "Free coaching + stipend",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://depwd.gov.in",
    documents: ["Disability Certificate", "Education Proof", "Aadhaar Card"],
    icon: "Book",
    source: "",
    publishDate: "",
  },
  {
    name: "Mahatma Jyotiba Phule Jan Arogya Yojana",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Health insurance scheme covering major treatments and surgeries.",
    eligibilityCriteria: {
      incomeGroup: "Economically weaker sections including disabled persons",
    },
    benefits: "₹1.5 - ₹2.5 lakh health coverage",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://www.jeevandayee.gov.in",
    documents: ["Aadhaar Card", "Ration Card", "Medical Documents"],
    icon: "HeartPulse",
    source: "",
    publishDate: "",
  },
  {
    name: "UDID Card Scheme",
    ministry: "Department of Empowerment of Persons with Disabilities",
    category: "Central Government",
    description: "Unique Disability ID card required for availing most government schemes.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
    },
    benefits: "Free ID card",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://www.swavlambancard.gov.in",
    documents: ["Disability Certificate", "Aadhaar Card", "Photo"],
    icon: "IdCard",
    source: "",
    publishDate: "",
  },

  // ── Central Government Core Schemes (1–10) ────────────────────────────────
  {
    name: "Pradhan Mantri Disability Pension Scheme",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "Monthly pension for disabled individuals below poverty line.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      incomeGroup: "BPL",
    },
    benefits: "₹2,000/month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "BPL Card", "Aadhaar Card", "Bank Details"],
    icon: "Building2",
    source: "",
    publishDate: "",
  },
  {
    name: "Deen Dayal Disabled Rehabilitation Scheme (DDRS)",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "Supports NGOs working for the welfare and rehabilitation of persons with disabilities.",
    eligibilityCriteria: {
      applicant: "NGOs working for PwD welfare",
    },
    benefits: "Up to ₹10 lakh",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/scheme/deendayal-disabled-rehabilitation-scheme-to-promote-voluntary-action-for-persons-with-disabilities-ddrs-scheme/",
    documents: ["NGO Registration", "Project Proposal", "Audited Accounts"],
    icon: "Heart",
    source: "",
    publishDate: "",
  },
  {
    name: "Assistive Devices Scheme",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Provides free assistive devices to persons with disabilities.",
    eligibilityCriteria: {
      disabilityCategories: "All categories",
    },
    benefits: "Free devices worth ₹8,000",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/scheme/7-scheme-of-assistance-to-disabled-persons-for-purchase-fitting-of-aids-appliances-adip-scheme/",
    documents: ["Disability Certificate", "Income Certificate", "Medical Report"],
    icon: "Building2",
    source: "",
    publishDate: "",
  },
  {
    name: "Disability Allowance Scheme",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Monthly allowance for persons with disabilities.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      incomeCriteria: "As per guidelines",
    },
    benefits: "₹1,500/month",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Income Certificate", "Aadhaar Card"],
    icon: "IndianRupee",
    source: "",
    publishDate: "",
  },
  {
    name: "Scholarship for Disabled Students",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "Annual scholarship for students with disabilities based on merit.",
    eligibilityCriteria: {
      disabilityPercentage: "≥40%",
      basis: "Merit",
    },
    benefits: "₹12,000/year",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "School/College",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/provider/state-government/",
    documents: ["Disability Certificate", "Academic Records", "Bank Details"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Health Insurance for PwD",
    ministry: "Ministry of Health & Family Welfare",
    category: "Healthcare",
    description: "Comprehensive health insurance scheme for persons with disabilities.",
    eligibilityCriteria: {
      eligibility: "All PwD with valid certificate",
    },
    benefits: "₹5 lakh coverage",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Aadhaar Card", "Family Income Proof"],
    icon: "Heart",
    source: "",
    publishDate: "",
  },
  {
    name: "Employment Guarantee Scheme for PwD",
    ministry: "Ministry of Labour & Employment",
    category: "Central Government",
    description: "Guaranteed employment scheme for persons with disabilities aged 18–65.",
    eligibilityCriteria: {
      ageRange: "18–65 years",
      disabilityPercentage: "≥40%",
    },
    benefits: "₹300/day",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Age Proof", "Skills Certificate"],
    icon: "Briefcase",
    source: "",
    publishDate: "",
  },
  {
    name: "Skill Development Scheme for PwD",
    ministry: "Ministry of Skill Development & Entrepreneurship",
    category: "Financial Aid",
    description: "Free skill development training with stipend for persons with disabilities.",
    eligibilityCriteria: {
      ageRange: "18–45 years",
      educationLevel: "Basic education",
    },
    benefits: "Free training + ₹5,000 stipend",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Basic Education",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Educational Qualification", "Bank Details"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Housing Assistance for PwD",
    ministry: "Government of Maharashtra",
    category: "State Government",
    description: "Housing support for BPL and landless persons with disabilities.",
    eligibilityCriteria: {
      incomeGroup: "BPL",
      landStatus: "Landless",
    },
    benefits: "Up to ₹3 lakh",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Land Documents", "BPL Certificate"],
    icon: "Building2",
    source: "",
    publishDate: "",
  },
  {
    name: "Transport Subsidy for PwD",
    ministry: "Ministry of Road Transport & Highways",
    category: "Financial Aid",
    description: "Travel fare discount for persons with valid disability certificate.",
    eligibilityCriteria: {
      eligibility: "Valid disability certificate holder",
    },
    benefits: "50% fare discount",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "#",
    documents: ["Disability Certificate", "Photo ID"],
    icon: "IndianRupee",
    source: "",
    publishDate: "",
  },

  // ── Official Maharashtra Schemes ──────────────────────────────────────────
  {
    name: "District Disability Rehabilitation Centres (DDRC)",
    ministry: "Persons with Disabilities Welfare Dept, Maharashtra",
    category: "State Government",
    description: "District-level centres providing rehabilitation services, therapy, counselling, assistive devices, skill development, and support to PwDs.",
    eligibilityCriteria: {
      eligibility: "PwDs needing therapy, counselling, skill development",
    },
    benefits: "Rehabilitation services",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/scheme/district-disability-rehabilitation-centre-ddrc/",
    documents: ["Disability Certificate", "ID Proof"],
    icon: "Building2",
    source: "Persons with Disabilities Welfare Dept, Maharashtra",
    publishDate: "11/01/2024",
  },
  {
    name: "SIPDA – Implementation of the Rights of Persons with Disabilities Act 2016",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "Ensures implementation of the RPwD Act 2016, promoting accessibility, equal rights, and welfare of persons with disabilities.",
    eligibilityCriteria: {
      eligibility: "Persons with disabilities across all categories",
    },
    benefits: "Legal protection & accessibility initiatives",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/schemes-programmes/#sipda",
    documents: ["According to scheme guidelines"],
    icon: "CheckCircle",
    source: "Persons with Disabilities Welfare Dept, Maharashtra",
    publishDate: "11/01/2024",
  },
  {
    name: "Free Coaching & Educational Support for Disabled Students",
    ministry: "Persons with Disabilities Welfare Dept, Maharashtra",
    category: "State Government",
    description: "Free coaching, academic support, and exam concessions provided to disabled students across Maharashtra.",
    eligibilityCriteria: {
      eligibility: "Students with disabilities",
    },
    benefits: "Free coaching / exam support",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "School/College",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/scheme/free-coaching-scholarship-for-students-with-disabilities/",
    documents: ["Disability Certificate", "School/College ID"],
    icon: "GraduationCap",
    source: "Persons with Disabilities Welfare Dept, Maharashtra",
    publishDate: "03/12/2023",
  },
  {
    name: "State Awards & Matrimonial Incentives for Disabled Persons",
    ministry: "Persons with Disabilities Welfare Dept, Maharashtra",
    category: "State Government",
    description: "State awards for merit/achievement and incentives for marriage among eligible disabled persons.",
    eligibilityCriteria: {
      eligibility: "Eligible disabled persons as per rules",
    },
    benefits: "One-time incentives / awards",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "",
    isActive: true,
    applyLink: "https://divyangkalyan.maharashtra.gov.in/provider/state-government/",
    documents: ["Disability Certificate", "Eligibility Documents"],
    icon: "Heart",
    source: "Persons with Disabilities Welfare Dept, Maharashtra",
    publishDate: "02/12/2023",
  },

  // ── Central Scholarship Schemes (20–25) ───────────────────────────────────
  {
    name: "National Overseas Scholarship For Students With Disabilities",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "A full scholarship for Students with Disabilities to pursue Master's or PhD courses in listed foreign universities.",
    eligibilityCriteria: {
      educationLevel: "Master's or PhD abroad",
    },
    benefits: "Full scholarship – Tuition + Living + Travel",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Master's / PhD",
    isActive: true,
    applyLink: "https://socialjustice.gov.in",
    documents: ["Disability Certificate", "Admission Proof", "Educational Records", "Income Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Post Matric Scholarship for Students With Disabilities",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "A scholarship scheme for Students with Disabilities pursuing Class 11–12, Diploma, Undergraduate, Postgraduate and other recognized courses.",
    eligibilityCriteria: {
      educationLevel: "Class 11–12, Diploma, UG, PG",
    },
    benefits: "Tuition + Books + Maintenance Allowance",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Class 11 and above",
    isActive: true,
    applyLink: "https://scholarships.gov.in",
    documents: ["Disability Certificate", "Admission Proof", "Bank Details", "Income Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Top Class Education For Students With Disabilities",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "A national scholarship for SwDs pursuing full-time higher education in government-notified top institutions in India.",
    eligibilityCriteria: {
      educationLevel: "Full-time courses beyond Class 12 in notified institutions",
    },
    benefits: "Books + Tuition + Living Allowance",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Post Class 12",
    isActive: true,
    applyLink: "https://scholarships.gov.in",
    documents: ["Disability Certificate", "Admission Proof", "Fee Receipts"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "AICTE – Saksham Scholarship Scheme (Degree)",
    ministry: "All India Council for Technical Education (AICTE)",
    category: "Central Government",
    description: "A scholarship by AICTE to support specially-abled students pursuing technical degree programs in India.",
    eligibilityCriteria: {
      educationLevel: "AICTE-approved degree-level technical programs",
    },
    benefits: "₹50,000/year",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Degree (Technical)",
    isActive: true,
    applyLink: "https://www.aicte-india.org/schemes/students-development-schemes/scholarships",
    documents: ["Disability Certificate", "AICTE Approved Admission Proof"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Pre-Matric Scholarship For Students With Disabilities",
    ministry: "Ministry of Social Justice & Empowerment",
    category: "Central Government",
    description: "A scholarship for Class 9–10 Students with Disabilities studying in government or government-recognized schools.",
    eligibilityCriteria: {
      educationLevel: "Class 9–10",
    },
    benefits: "Book Grant + Maintenance Allowance",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Class 9–10",
    isActive: true,
    applyLink: "https://scholarships.gov.in",
    documents: ["Disability Certificate", "School ID", "Income Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "AICTE – Saksham Scholarship Scheme (Diploma)",
    ministry: "All India Council for Technical Education (AICTE)",
    category: "Central Government",
    description: "Scholarship by AICTE for specially-abled students pursuing diploma-level technical courses.",
    eligibilityCriteria: {
      educationLevel: "AICTE-approved diploma technical programs",
    },
    benefits: "₹50,000/year",
    deadline: null,
    maxIncome: null,
    disabilityTypes: ["All"],
    educationRequired: "Diploma (Technical)",
    isActive: true,
    applyLink: "https://www.aicte-india.org/schemes/students-development-schemes/scholarships",
    documents: ["Disability Certificate", "Admission Proof"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },

  // ── Additional Schemes (26–34) ────────────────────────────────────────────
  {
    name: "Skill Loan Scheme",
    ministry: "Ministry of Skill Development & Entrepreneurship",
    category: "Central Government",
    description: "Loan scheme to support students pursuing technical and skill-based courses.",
    eligibilityCriteria: {
      educationLevel: "Admitted in ITIs, Polytechnics, or recognized institutions",
    },
    benefits: "Up to ₹1,50,000 loan",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "ITI / Polytechnic",
    isActive: true,
    applyLink: "https://www.vidyalakshmi.co.in/",
    documents: ["Admission Proof", "Identity Proof", "Bank Details"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "ICAR Junior Research Fellowship (PG Studies)",
    ministry: "Indian Council of Agricultural Research (ICAR)",
    category: "Central Government",
    description: "Fellowship awarded by ICAR to encourage higher education in agriculture and allied sciences.",
    eligibilityCriteria: {
      educationLevel: "Master's degree in agricultural sciences",
    },
    benefits: "Monthly Fellowship + Contingency Grant",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "Master's (Agriculture)",
    isActive: true,
    applyLink: "https://icar.org.in/",
    documents: ["UG Degree Certificate", "Entrance Qualification Proof"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "ICAR Senior Research Fellowship (PhD)",
    ministry: "Indian Council of Agricultural Research (ICAR)",
    category: "Central Government",
    description: "Senior research fellowship for PhD students in agriculture and allied disciplines.",
    eligibilityCriteria: {
      educationLevel: "PhD in agricultural sciences",
    },
    benefits: "Monthly Fellowship + Research Grant",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "PhD (Agriculture)",
    isActive: true,
    applyLink: "https://icar.org.in/",
    documents: ["PG Degree Certificate", "Research Proposal"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "National Solar Science Fellowship Programme",
    ministry: "Ministry of New and Renewable Energy",
    category: "Central Government",
    description: "Fellowship program to promote solar energy research.",
    eligibilityCriteria: {
      eligibility: "Scientists and engineers in solar energy research",
    },
    benefits: "Research Fellowship",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "",
    isActive: true,
    applyLink: "https://mnre.gov.in/",
    documents: ["Research Proposal", "Qualification Certificates"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Post-Graduate Scholarships for SC/ST Candidates",
    ministry: "University Grants Commission (UGC)",
    category: "Central Government",
    description: "Scholarship scheme to support SC/ST students in professional postgraduate studies.",
    eligibilityCriteria: {
      category: "SC/ST",
      educationLevel: "Postgraduate professional courses",
    },
    benefits: "Scholarship for Professional PG Courses",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "Postgraduate",
    isActive: true,
    applyLink: "https://scholarships.gov.in/",
    documents: ["Caste Certificate", "Admission Proof", "Income Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "PM-USP Central Sector Scholarship Scheme",
    ministry: "Ministry of Education",
    category: "Central Government",
    description: "Scholarship to provide financial support to deserving students for college and university education.",
    eligibilityCriteria: {
      eligibility: "Meritorious students from low-income families",
    },
    benefits: "Financial Assistance for Higher Education",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "Higher Education",
    isActive: true,
    applyLink: "https://scholarships.gov.in/",
    documents: ["12th Marksheet", "Income Certificate", "Admission Proof"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Free Education for Sports Medal Winners",
    ministry: "University Grants Commission (UGC)",
    category: "Central Government",
    description: "Financial assistance for sports medal winners studying in universities/colleges.",
    eligibilityCriteria: {
      eligibility: "Sports medal winners/participants in national or international events",
    },
    benefits: "Full Tuition Fee Waiver",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "College/University",
    isActive: true,
    applyLink: "https://www.ugc.ac.in/",
    documents: ["Sports Certificate", "Admission Proof"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "NITI Internship Scheme",
    ministry: "NITI Aayog",
    category: "Central Government",
    description: "Internship scheme providing exposure to various divisions within NITI Aayog.",
    eligibilityCriteria: {
      eligibility: "UG/PG students and research scholars in recognized institutions",
    },
    benefits: "Internship Opportunity",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "UG/PG",
    isActive: true,
    applyLink: "https://www.niti.gov.in/internship",
    documents: ["College ID", "Bonafide Certificate", "Resume"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "DPIIT Internship Scheme",
    ministry: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    category: "Central Government",
    description: "Internship scheme by DPIIT for students and research scholars.",
    eligibilityCriteria: {
      eligibility: "UG/PG students and research scholars",
    },
    benefits: "Internship Opportunity",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "UG/PG",
    isActive: true,
    applyLink: "https://dpiit.gov.in/internship",
    documents: ["College ID", "Resume"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
  {
    name: "Post Graduate Merit Scholarship for Rank Holders",
    ministry: "University Grants Commission (UGC)",
    category: "Central Government",
    description: "Merit scholarship scheme for university rank holders at undergraduate level pursuing PG studies.",
    eligibilityCriteria: {
      eligibility: "University rank holders at UG level",
      educationLevel: "Pursuing PG studies",
    },
    benefits: "Scholarship for 2 Years",
    deadline: null,
    maxIncome: null,
    disabilityTypes: [],
    educationRequired: "Postgraduate",
    isActive: true,
    applyLink: "https://scholarships.gov.in/",
    documents: ["UG Marksheet", "Rank Certificate"],
    icon: "GraduationCap",
    source: "",
    publishDate: "",
  },
];

// ── Seed Function ─────────────────────────────────────────────────────────────
// Run this ONCE to populate Firestore with all scheme listings
// e.g., call seedSchemes() from an admin page or a one-time script
export const seedSchemes = async () => {
  const schemesRef = collection(db, "schemes");
  const results = await Promise.allSettled(
    schemesData.map((scheme) =>
      addDoc(schemesRef, { ...scheme, createdAt: serverTimestamp() })
    )
  );

  const succeeded = results.filter((r) => r.status === "fulfilled").length;
  const failed = results.filter((r) => r.status === "rejected").length;

  console.log(`✅ Seeded ${succeeded} schemes successfully.`);
  if (failed > 0) console.warn(`⚠️ ${failed} schemes failed to seed.`);
};