// features/performance/components/AchievementBadges.tsx
// Visual dynamic badge showcase generated by the deterministic Badge Rule Engine

import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  Award,
  Flame,
  BookOpen,
  Brain,
  Target,
  Code2,
  Rocket,
  Medal,
  ScrollText,
  Sparkles,
  Lock,
  CheckCircle2,
  Trophy,
} from "lucide-react";
import type { BadgeItem } from "../types/performance.types";

interface AchievementBadgesProps {
  badges: BadgeItem[];
}

const ICON_COMPONENTS: Record<string, any> = {
  Trophy,
  Flame,
  BookOpen,
  Brain,
  Target,
  Code2,
  Rocket,
  Medal,
  ScrollText,
  Sparkles,
};

export const AchievementBadges: React.FC<AchievementBadgesProps> = ({ badges }) => {
  const unlocked = badges.filter((b) => b.unlocked);
  const totalPoints = unlocked.reduce((acc, b) => acc + b.points, 0);

  return (
    <div className="space-y-6">
      {/* 1. Badges Summary Banner */}
      <Card className="rounded-3xl border border-border/80 bg-gradient-to-r from-amber-500/10 via-purple-500/5 to-transparent backdrop-blur-xl">
        <CardContent className="p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="border-amber-500/30 text-amber-600 dark:text-amber-400 text-[10px] font-bold">
                Dynamic Badge Engine
              </Badge>
              <span className="text-xs text-muted-foreground">
                Evaluated from real platform activity
              </span>
            </div>
            <h3 className="text-xl font-black text-foreground">
              Official Student Achievement Badges
            </h3>
            <p className="text-xs text-muted-foreground max-w-xl">
              Earned dynamically based on verified quiz accuracy, study streaks, capstone engineering projects, and national competition victories.
            </p>
          </div>

          <div className="flex items-center gap-4 shrink-0 bg-card/80 border border-border/60 p-4 rounded-2xl">
            <div className="text-right">
              <div className="text-xs text-muted-foreground font-semibold">Reputation Points</div>
              <div className="text-2xl font-black text-amber-500">{totalPoints} pts</div>
            </div>
            <div className="h-8 w-px bg-border/60" />
            <div>
              <div className="text-xs text-muted-foreground font-semibold">Unlocked</div>
              <div className="text-2xl font-black text-primary">
                {unlocked.length} <span className="text-xs font-normal text-muted-foreground">/ {badges.length}</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* 2. Badges Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {badges.map((badge) => {
          const IconComp = ICON_COMPONENTS[badge.icon] || Award;

          return (
            <Card
              key={badge.id}
              className={`rounded-2xl border transition-all duration-300 ${
                badge.unlocked
                  ? "border-amber-500/40 bg-gradient-to-br from-amber-500/10 via-card/70 to-card/40 backdrop-blur-sm shadow-md hover:scale-[1.02]"
                  : "border-border/60 bg-card/40 opacity-75 grayscale-[20%]"
              }`}
            >
              <CardContent className="p-5 space-y-4">
                <div className="flex items-start justify-between gap-3">
                  <div
                    className={`p-3 rounded-2xl border ${
                      badge.unlocked
                        ? "bg-amber-500/20 border-amber-500/40 text-amber-500 shadow-inner"
                        : "bg-muted border-border/60 text-muted-foreground"
                    }`}
                  >
                    <IconComp className="h-6 w-6" />
                  </div>

                  <div className="flex flex-col items-end gap-1">
                    <Badge
                      variant={badge.unlocked ? "default" : "secondary"}
                      className={`text-[10px] font-bold ${
                        badge.unlocked ? "bg-amber-500 text-white" : ""
                      }`}
                    >
                      {badge.unlocked ? "✓ Unlocked" : "🔒 In Progress"}
                    </Badge>
                    <span className="text-[10px] font-mono text-muted-foreground font-semibold">
                      +{badge.points} pts
                    </span>
                  </div>
                </div>

                <div className="space-y-1">
                  <h4 className="font-bold text-sm text-foreground flex items-center gap-1.5">
                    {badge.name}
                  </h4>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {badge.description}
                  </p>
                </div>

                {/* Progress bar toward unlock */}
                <div className="space-y-1 pt-1 border-t border-border/40">
                  <div className="flex justify-between text-[11px] font-medium text-muted-foreground">
                    <span className="truncate max-w-[170px]">{badge.criteria}</span>
                    <span className="font-bold text-foreground">{badge.progress}%</span>
                  </div>
                  <Progress
                    value={badge.progress}
                    className={`h-1.5 ${badge.unlocked ? "bg-amber-500/20" : "bg-muted"}`}
                  />
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
};
